(cl:defpackage uh_study-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "FACEPOSESRV"
   "<FACEPOSESRV-REQUEST>"
   "FACEPOSESRV-REQUEST"
   "<FACEPOSESRV-RESPONSE>"
   "FACEPOSESRV-RESPONSE"
  ))

