(cl:defpackage face_detector-msg
  (:use )
  (:export
   "<FACEDETECTORACTIONFEEDBACK>"
   "FACEDETECTORACTIONFEEDBACK"
   "<FACEDETECTORFEEDBACK>"
   "FACEDETECTORFEEDBACK"
   "<FACEDETECTORACTIONRESULT>"
   "FACEDETECTORACTIONRESULT"
   "<FACEDETECTORRESULT>"
   "FACEDETECTORRESULT"
   "<FACEDETECTORGOAL>"
   "FACEDETECTORGOAL"
   "<FACEDETECTORACTIONGOAL>"
   "FACEDETECTORACTIONGOAL"
   "<FACEDETECTORACTION>"
   "FACEDETECTORACTION"
  ))

