auto_exposure:     False
exposure:          0.009
auto_gain:         True
gain:              1
auto_whitebalance: True
frame_id: high_def_optical_frame_master
stream_bytes_per_second: 54000000
auto_adjust_stream_bytes_per_second: False
binning_x:         1
binning_y:         1
exposure:          2.5e-05
height:            480
width:             640
trigger_mode:      streaming
whitebalance_blue: 100
whitebalance_red:  100
x_offset:          500
y_offset:          500
